INSERT INTO DERBYUSER.ESCRIBE(IDAUTOR, IDLIBRO) VALUES (01, 01); -- García Márquez escribió Cien años de soledad
INSERT INTO DERBYUSER.ESCRIBE(IDAUTOR, IDLIBRO) VALUES (02, 02); -- Federico García Lorca escribió Bodas de Sangre
INSERT INTO DERBYUSER.ESCRIBE(IDAUTOR, IDLIBRO) VALUES (03, 03); -- Carlos Zafón escribió La Sombra del Viento
INSERT INTO DERBYUSER.ESCRIBE(IDAUTOR, IDLIBRO) VALUES (04, 04); -- Almudena Grandes escribió Las edades de Lulú
INSERT INTO DERBYUSER.ESCRIBE(IDAUTOR, IDLIBRO) VALUES (05, 05); -- Eduardo Mendoza escribió El rey recibe
INSERT INTO DERBYUSER.ESCRIBE(IDAUTOR, IDLIBRO) VALUES (06, 06); -- Ana María Matute escribió Los Abel
INSERT INTO DERBYUSER.ESCRIBE(IDAUTOR, IDLIBRO) VALUES (07, 07); -- Camilo José Cela escribió La Colmena
INSERT INTO DERBYUSER.ESCRIBE(IDAUTOR, IDLIBRO) VALUES (08, 08); -- Fernando Eslava escribióEl Doble
INSERT INTO DERBYUSER.ESCRIBE(IDAUTOR, IDLIBRO) VALUES (09, 09); -- Beatriz Aguilera escribióLa sombra del almirante
INSERT INTO DERBYUSER.ESCRIBE(IDAUTOR, IDLIBRO) VALUES (10, 10);   -- Laura Es
